### ISSUE TITLE
GeoFence Entry Empty Message Body

### ISSUE THREAD

**Issue by harishios** [phunware/maas-engagement-ios-sdk#22]
`PWEngagement` SDK responds with the `GEOFENCE_ENTRY` event, but the message body seems to be empty, but the same code is works with the Trial Application provided by Phunware. 

Below is the response from my application.

`details =     {
        category = Network;
        event = "GEOFENCE_ENTRY";
        response =         {
            geoFences =             {
                in =                 (
                );
                minus =                 (
                );
                plus =                 (
                );
            };
            messages =             (
            );
        };
    };
    message = "Entry geofence response";
    service = PWEngagement;
    timestamp = "**";
    type = PWLogTypeDebug;`

This is the response from Phunware Trial Application:

`details =     {
        category = Network;
        event = "GEOFENCE_ENTRY";
        response =         {
            geoFences =             {
                in =                 (
                );
                minus =                 (
                );
                plus =                 (
                );
            };
            messages =             (
                                {
                    campaignId = 23473;
                    campaignType = "GEOFENCE_ENTRY";
                    messageMetadata =                     {
                        test = test;
                    };
                    notification =                     {
                        message = "Hello";
                        title = "Hello, Welcome!";
                    };
                    promotionExpirationDate = "";
                }
            );
        };
    };
    message = "Entry geofence response";
    service = PWEngagement;
    timestamp = "*** ";
    type = PWLogTypeDebug;`.

Let me know what I'm missing.

**Comment by tstump-phunware** [comment]
Closing, as this is not an SDK issue, rather a configuration issue on the back end.
